version: '3.8'

volumes:
  mongodb_data:

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./build/docker/web/Dockerfile
    restart: always
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./.env
    ports:
      - "27018:27017"
